
add_newline = true

[character]
success_symbol = "[ïŒƒ ](blue)"
error_symbol = "[îˆ± ](red)"

[directory]
read_only = " ğŸ”’"

[time]
disabled = true
format = 'ğŸ•™[\[ $time \]]($style) '
time_format = "%T"
style = "bright-white"

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "ğŸ”Œ"
discharging_symbol = "âš¡"

[[battery.display]]
threshold = 30
style = "bold red"

[hostname]
ssh_only = true
format = "<[$hostname]($style)>"
trim_at = "-"
style = "bold dimmed white"
disabled = false

[sudo]
style = "green"
symbol = "ïš¤ "
disabled = false

[git_branch]
symbol = "ï˜ "
style = "purple"
format = "on [$symbol$branch]($style) "

[nodejs]
format = "with [ï¢˜ $version](green) "

[lua]
format = "with [î˜  $version](blue) "
